ALTER TABLE orders ADD COLUMN total_amount NUMERIC(19,4) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN total_currency VARCHAR(3) NOT NULL DEFAULT 'USD';
ALTER TABLE orders ALTER COLUMN total_amount DROP DEFAULT;
ALTER TABLE orders ALTER COLUMN total_currency DROP DEFAULT;
