spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/autoshipper}
    username: ${DB_USERNAME:autoshipper}
    password: ${DB_PASSWORD:autoshipper}
  jpa:
    show-sql: true
  flyway:
    enabled: true

logging:
  level:
    com.autoshipper: DEBUG
