package com.autoshipper.fulfillment.handler.dto

data class OrderResponse(
    val id: String,
    val skuId: String,
    val vendorId: String,
    val customerId: String,
    val totalAmount: String,
    val totalCurrency: String,
    val status: String,
    val quantity: Int,
    val supplierOrderId: String? = null,
    val failureReason: String? = null,
    val trackingNumber: String?,
    val carrier: String?,
    val estimatedDelivery: String?,
    val channel: String? = null,
    val channelOrderId: String? = null,
    val channelOrderNumber: String? = null,
    val shippingCustomerName: String? = null,
    val shippingAddress: String? = null,
    val shippingCity: String? = null,
    val shippingProvince: String? = null,
    val shippingCountry: String? = null,
    val shippingCountryCode: String? = null,
    val shippingZip: String? = null,
    val shippingPhone: String? = null,
    val createdAt: String,
    val updatedAt: String
)
